# Generated by Django 3.2.6 on 2021-08-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='title',
        ),
    ]
