# Generated by Django 3.2.6 on 2021-10-04 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('customers', '0002_remove_customer_event'),
        ('events', '0003_auto_20211001_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='customer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='customers.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.project'),
        ),
    ]
