# Generated by Django 3.2.6 on 2021-10-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('wait_payment', 'wait_payment'), ('approved', 'approved'), ('ended', 'ended'), ('canceled', 'canceled')], default='new', max_length=255),
        ),
    ]
