# Generated by Django 3.2.6 on 2021-10-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20211011_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[(0, 'new'), (1, 'approved'), (2, 'completed'), (3, 'canceled')], default=0, max_length=255),
        ),
    ]
