# Generated by Django 3.2.6 on 2021-10-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, max_length=255),
        ),
    ]
