# Generated by Django 3.2.6 on 2021-11-09 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-pk'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
