# Generated by Django 3.2.6 on 2021-10-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'success'), ('danger', 'danger'), ('info', 'info'), ('warning', 'warning'), ('secondary', 'secondary'), ('dark', 'dark'), ('white', 'white')], default='primary', max_length=255),
        ),
    ]
