# Generated by Django 3.2.6 on 2021-10-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(choices=[('primary', 'primary'), ('success', 'success'), ('danger', 'danger'), ('info', 'info'), ('warning', 'warning'), ('dark', 'dark')], default='primary', max_length=255),
        ),
    ]
