# Generated by Django 3.2.6 on 2021-10-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='working_hours',
            field=models.CharField(default='08:00-17:00', max_length=20),
            preserve_default=False,
        ),
    ]
