# Generated by Django 3.2.6 on 2021-10-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='Asia/Tbilisi', max_length=255),
            preserve_default=False,
        ),
    ]
