# Generated by Django 3.2.6 on 2021-10-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='working_hours',
            field=models.CharField(default='09:00:00-18:00:00', max_length=20),
        ),
    ]
