# Generated by Django 3.2.6 on 2021-10-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='welcome_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
