# Generated by Django 3.2.6 on 2021-09-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210908_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='_avatar',
            new_name='avatar',
        ),
    ]
