# Generated by Django 3.2.6 on 2021-09-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename__avatar_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='', null=True, upload_to='users/profiles/avatars/'),
        ),
    ]
