# Generated by Django 3.2.6 on 2021-09-27 23:36

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.AccountUserManager()),
            ],
        ),
    ]
