# Generated by Django 3.2.6 on 2021-10-04 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='event',
        ),
    ]
