# Generated by Django 3.2.6 on 2021-10-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_board_unique_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='color',
            field=models.CharField(choices=[('primary', 'primary'), ('success', 'success'), ('danger', 'danger'), ('info', 'info'), ('warning', 'warning'), ('dark', 'dark')], default='primary', max_length=255),
        ),
    ]
