# Generated by Django 3.2.6 on 2021-10-15 05:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0007_board_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board',
            new_name='BoardColumn',
        ),
        migrations.AlterModelOptions(
            name='boardcolumn',
            options={'verbose_name': 'BoardColumn', 'verbose_name_plural': 'BoardColumns'},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='board',
            new_name='board_column',
        ),
    ]
