# Generated by Django 3.2.6 on 2021-10-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20211015_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='board_order',
            field=models.IntegerField(default=0),
        ),
    ]
