# Generated by Django 3.2.6 on 2021-10-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customer_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='boardcolumn',
            name='unique_is_primary',
        ),
    ]
