// Auth module
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE'
export const REFRESH_TOKEN = 'REFRESH_TOKEN'
export const SIGNOUT = 'SIGNOUT'

// Calendar module
export const GET_EVENTS = 'GET_EVENTS'
export const CREATE_EVENT = 'CREATE_EVENT'
export const UPDATE_EVENT = 'UPDATE_EVENT'
export const DELETE_EVENT = 'DELETE_EVENT'
export const APPROVE_EVENT = 'APPROVE_EVENT'
// Set error
export const SET_ERROR = 'SET_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'

// UserProfile
export const SET_USERPROFILE = 'SET_USERPROFILE'
export const UPDATE_USERPROFILE = 'UPDATE_USERPROFILE'
export const UPDATE_USERPROFILE_AVATAR = 'UPDATE_USERPROFILE_AVATAR'
export const REMOVE_USERPROFILE_AVATAR = 'REMOVE_USERPROFILE_AVATAR'

// Projects
export const SET_PROJECTS = 'SET_PROJECTS'
export const CREATE_PROJECT = 'CREATE_PROJECT'

// Customers

export const SET_CUSTOMERS = 'SET_CUSTOMERS'
